### ISSUE TITLE
docstrings

### ISSUE THREAD

**Issue by AFineDayFor** [emilianavt/OpenSeeFace#10]
comments are present often it seems; however, you're busy and could probs use a hand.
todo: update comment

**Comment by emilianavt** [comment]
More or improved documentation and comments would be very welcome.

**Comment by AFineDayFor** [comment]
> More or improved documentation and comments would be very welcome.

`^_^` mhm, hope you're well. It's not like it's missing all together, but I wanted to read over it so this works for me.
