### ISSUE TITLE
Vseeface

### ISSUE THREAD

**Issue by Nekosrule** [emilianavt/OpenSeeFace#11]
I tried to download your program and it says Failed-forbidden and I tried everything so it must be on your side.

**Comment by emilianavt** [comment]
This repository is about OpenSeeFace, not VSeeFace. VSeeFace downloads are hosted [here](https://github.com/emilianavt/VSeeFaceReleases/releases) on github. I'm not sure how they could give a download error. If it's not on your side, it would seem to be an issue with github's servers, but the download works for me.

**Comment by drojf** [comment]
@Nekosrule Github is actually blocked by some ISPs in some countries. You can try using a free VPN like https://protonvpn.com/ to see if the download goes through when you connect via a different country.

**Comment by drojf** [comment]
@Nekosrule to double check that it's a problem on your side, try downloading via a VPN like https://protonvpn.com/ and downloading through another country than your own.
