### ISSUE TITLE
Tracker taking long time after some frames 

### ISSUE THREAD

**Issue by trilokpadhi** [emilianavt/OpenSeeFace#14]
Hi @emilianavt 
Thanks for the nice repo . While running the code , the tracker takes a long time after some frames , I have attached the screenshot here , can you please tell what may be the possible reason ? You can see that in the attached screenshot that , after 22 ms , the tracker takes a longer time upto 2398 ms which is almost 100 times more . 
Thanks
Trilok

![image](https://user-images.githubusercontent.com/20143249/103336039-ea3aae80-4a9c-11eb-96b2-7742a8fa911e.png)

**Comment by emilianavt** [comment]
Is there any other CPU intensive process running? I noticed that having other heavy processes running could make the tracking time vary a lot, especially when set to single threaded. I don't think there is anything in the code itself that would cause the time to change much. Even something quite simple like cropping out the face seems to randomly take much longer in the screenshot, so I'd blame the OS not giving it enough CPU time. You can try increasing the number of threads with `-m`.

**Comment by trilokpadhi** [comment]
Hi @emilianavt 
Thanks for your reply , but I ran the code again in the local machine with latest code from the repository and you can see in the attached screenshot that in alternate frame proccesing , the cropping time and tracking time almost doubles .
I guess there is some process in the code that takes time .
can you please help me with this ?
Thanks
Trilok
![image](https://user-images.githubusercontent.com/20143249/103356558-2ab71e00-4ad7-11eb-91be-b20154446516.png)

**Comment by emilianavt** [comment]
What options are you running the tracking with? Defaults?

**Comment by trilokpadhi** [comment]
Yes ,I am running it with the default values

**Comment by emilianavt** [comment]
Does it happen if you set `--discard-after 0`?
