### ISSUE TITLE
Model architecture

### ISSUE THREAD

**Issue by GLivshits** [emilianavt/OpenSeeFace#15]
Hello. Probably, my question is quite stupid, but nvm:
Ur model should work in a detector fashion (fully convolutional). But ur model (at least the large one) requires a precise image shape (224x224). Can you briefly describe the architecture?

**Comment by emilianavt** [comment]
It's basically MobileNet V3 with some UNet upscaling layers on top that also get fed earlier residuals and a final convolution in three groups. It is fully convolutional and should work at any shape. However, when I tested the landmarking models at other shapes, I did not get reasonable results unless I retrained it at that shape. I'm not sure why. The face detection model however can be exported at other shapes to ONNX and does work. The original pytorch weights can be found in #1.
