### ISSUE TITLE
Pytorch model problems 

### ISSUE THREAD

**Issue by GrigorySamokhin** [emilianavt/OpenSeeFace#16]
Hello! Thanks for your work! 
I have some problem when running model.py file 
<img width="841" alt="Screenshot 2021-03-17 at 18 04 59" src="https://user-images.githubusercontent.com/47357694/111489564-4b445b00-874b-11eb-8daf-c426a96ec200.png">
And what means "geffnet.mobilenetv3._gen_mobilenet_v3 needs to be patched to return the parameters instead of instantiating the network" ?

**Comment by emilianavt** [comment]
It means that [here](https://github.com/rwightman/gen-efficientnet-pytorch/blob/master/geffnet/mobilenetv3.py#L167), `model_kwargs` needs to be returned instead of `model`. Perhaps after that change is made, it will run properly.
