### ISSUE TITLE
gaze estimation output format

### ISSUE THREAD

**Issue by hwuebben** [emilianavt/OpenSeeFace#2]
Hey there,

First of all thanks for the awesome work!

I`m trying to grab the gaze estimation results but do not understand the format of the data. 
I concluded that the second and third (indices 1 and 2) entries of the eye_state variable show the current gaze, but what exactly do the numbers mean? 
Is the gaze relative to the head position or the camera? 
Also what is the immediate output of the gaze model? 

Can you maybe give me some clarification?

Thank you and all the best!

**Comment by hwuebben** [comment]
Ah so I guess I misunderstood the gaze estimation concept, the model does not provide a gaze vector but the exact position of the pupils' centers which I then can use to determine the gaze, right?

**Comment by emilianavt** [comment]
Hi and thank you!

Yes, that is correct. You can find the way I calculate the gaze directions here:
https://github.com/emilianavt/OpenSeeFace/blob/master/Unity/OpenSee.cs#L177

I basically assume an average human eyeball size and calculate the direction from its center to the pupil center.

> Also what is the immediate output of the gaze model?

It's a heatmap with with offsets. It works basically the same as the face landmarks, but only for a single landmark per eye.

**Comment by hwuebben** [comment]
thanks four reply!

What puzzles me about this calculation is that it doesn't seem to use the pupil centers, because points3D[68] and points3D[69] are the eyeball centers not the pupil centers, or am I wrong?

**Comment by emilianavt** [comment]
This seems to be solved, so I'll close this issue. If you have any other questions, please feel free to reopen it.
