### ISSUE TITLE
License of *.onnx files?

### ISSUE THREAD

**Issue by l1npengtul** [emilianavt/OpenSeeFace#20]
Hi! I am creating a rust crate for face alignment and was thinking if I could integrate this as one of the backends. I was wondering of the license terms of the models and if I could integrate them (with credit, of course).

**Comment by emilianavt** [comment]
Hi! Sure, please feel free to integrate them! It's the same [license](https://github.com/emilianavt/OpenSeeFace/blob/master/LICENSE) as the rest of the repository.

**Comment by l1npengtul** [comment]
Thanks!
