### ISSUE TITLE
minor typing problem, or it's just me

### ISSUE THREAD

**Issue by GogoMakesGames** [emilianavt/OpenSeeFace#23]
I would have put up a PR, but I wanted to run this by you real quick because I'm not super familiar with C# and there is a really good chance I just don't have something setup correctly. 

OpenSeeVRMDriver.cs seems to have a typing issue, lines below. `nowT` is a double, but the InterpolatedMap takes a float in that param. I'm more familiar with python, seems like this SHOULD implicitly cast, but Unity and Visual Studio both throw an error. If I cast it as a float inline, Unity seems happy like that. 

https://github.com/emilianavt/OpenSeeFace/blob/9a6eb20d834d002d0d63d56f389ecf32453d0a25/Examples/OpenSeeVRMDriver.cs#L346-L348

Does this sound like an actual thing, or am I missing something dumb like upgrading some .net stuff?

**Comment by emilianavt** [comment]
It looks like I actually forgot to update `OpenSeeInterpolation.cs` at some point. Thank you for letting me know! It should be fixed now.

**Comment by GogoMakesGames** [comment]
Welcome! Thanks for all the hard work you do on this. Every time I dive in to work with vsf or osf, I'm always very impressed!
