### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'fps'

### ISSUE THREAD

**Issue by fakedeltatime** [emilianavt/OpenSeeFace#25]
When trying to log the data with the --log-data parameter, I get the complaint ```AttributeError: 'Namespace' object has no attribute 'fps'```, and it refers to ```line 296``` in ```facetracker.py```, where ```args.fps``` is used instead of ```fps```. Changing this to ```fps``` seems to fix the problem. I don't know how to actually contribute this change so I'm creating this issue instead.

**Comment by fakedeltatime** [comment]
"Fix" is perhaps inaccurate as the fps value in the file seems to always be 0.

**Comment by emilianavt** [comment]
Hi and thank you for reporting this. I haven't actually used the `--log-data` function in a while, so I might have accidentially broken it at some point. I'll take a look at it.

**Comment by emilianavt** [comment]
This should be fixed now.
