### ISSUE TITLE
Real time face tracking 

### ISSUE THREAD

**Issue by jayp84847** [emilianavt/OpenSeeFace#26]
Thank you for sharing such a great project. Yet I am working on some project with real time face tracking where I am using dlib 68_face_landmarks.dat but its not stable and accurate somehow I found this project, I saw some links and examples and guess what its amazing. 

So how can I use this module in unity for real time face tracking. Or can you guide me which file should I use for real time face tracking. Or is there any chance we can create tracking module as .dat  file formats.

**Comment by emilianavt** [comment]
Hi, I'm happy you like it!

You can find a sample setup for using it to animate a 3D model of a character [here](https://github.com/emilianavt/OpenSeeFaceSample). The included scene shows a basic setup for setting up a head tracking IK target and animating VRM model blendshapes. You can also do more custom animations by reading the tracking data from the OpenSee component yourself, similar to the scripts in the examples folder, and then mapping them to whatever model properties you like in a custom script.

**Comment by jayp84847** [comment]
Can you tell me which one is face landmarks tracking module file.

**Comment by emilianavt** [comment]
The tracking models are inside the models folder. Landmark tracking models have filenames starting with `lm_`.

**Comment by jayp84847** [comment]
Thank you fir your support. I will try it.
