### ISSUE TITLE
any interest in supporting oak-d/oak-d-lite camera?

### ISSUE THREAD

**Issue by silverhikari** [emilianavt/OpenSeeFace#32]
as stated above do you have any interest in supporting the oak-d line of spatial 3d cameras?, as with the kickstarter that is going around they are now at the same price as the leap controller though that price will rise. the products use a open python sdk called depthai.

**Comment by emilianavt** [comment]
Those cameras look interesting, but OpenSeeFace is mainly concerned with inferring landmarks from RGB images and a putting together the final training dataset for the models was a lot of work. I'm unlikely to find the time or resources to put together anything remotely similar for depth cameras.

**Comment by TheMasterofBlubb** [comment]
@silverhikari theoretically you can take the onnx model and convert it to OpenVino so it run on the Oak-D.

I got a OAK-D Lite and will try to make it work with VSeeFace. If i dont forget i can inform you if my experiment works out.


@emilianavt the OAK-Ds have RGB cameras too, so technically you only need to convert the model (there is a python script for that) and interface the camera instead of calling the CNN yourself.

Using the Position data from depthcamera is more of a bonus (or in my case for handtracking instead of a leapmotion)

**Comment by emilianavt** [comment]
I see, if they have RGB too it should work!

**Comment by TheMasterofBlubb** [comment]
yep there is a 4k RGB camera (the middle one usually), but also the stereo cameras are accessible individually as black and white cams (480p iirc)
The more interesting thing is to run the NN on the cam though as it has a AI-Chip onboard and then just grabbing the output data, hence the conversion to OpenVINO

**Comment by TheMasterofBlubb** [comment]
btw, do you by any chance have a layout of the OSC / VMC that VSeeFace uses (the message names so to speak)
im not very good with Japanese andd it seems not creating landmarks (if not specifically needed would be helping a lot)

**Comment by emilianavt** [comment]
The VMC protocol only transmits blendshapes and bones. OpenSeeFace's face tracking data is transmitted using custom UDP packets. It's probably easiest to understand from the parser: https://github.com/emilianavt/OpenSeeFace/blob/master/Unity/OpenSee.cs#L137

There is also some English language documentation on the VMC protocol here: https://protocol.vmc.info/english.html

**Comment by TheMasterofBlubb** [comment]
Oh thank you for that link, i couldnt find that on the site, probably cause you come to the jap version from google.

Yep have found that parser, currently trying to reverse engineer where values are coming from and what they mean.

Im absolutely not familiar with python, so my small tool will be C# with some C++(sadly DepthAI has only Python and C++ APIs).

But i found some simple examples that include gaze and headtracking so if a converted model of yours wont work out of the box i will try to go with that one and try to match the OpenSee protocoll.

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>
________________________________

**Comment by emilianavt** [comment]
If you are not familiar with python, the trickier part might be figuring out the decoding for the model's output. The current code for that is a bit dense and optimized:

https://github.com/emilianavt/OpenSeeFace/blob/master/model.py#L168-L178

In some very early versions, there should be a more readable function for decoding landmarks in tracker.py though.

**Comment by PheebeUK** [comment]
@TheMasterofBlubb How did you get on with converting the model to OpenVino and generating OpenSEeFace compatible packets?
