### ISSUE TITLE
not support macbook

### ISSUE THREAD

**Issue by h310558606** [emilianavt/OpenSeeFace#34]
How can I use this project if I use a macbook?

**Comment by emilianavt** [comment]
Hi! I don't really know anything about macbooks, but I would assume if you have Python 3 installed, you can just use pip to install the dependencies and then run the scripts as normal, the same as with Linux or Windows.

**Comment by 0suu** [comment]
Thanks for the great project.
After installing the dependencies, I tried to run facetracker.py on my mac.
The program quits after a certain amount of time with no errors or other logs.
It asks for access to the camera, which I grant, but the camera is not in use.
If you have any idea how to run it, I would appreciate your help.

**Comment by emilianavt** [comment]
It should show some kind of output at least. Have you tried setting different resolutions with the -W and -H arguments?
