### ISSUE TITLE
Packets on 369 of facetracker.py fail with VPN enabled

### ISSUE THREAD

**Issue by AtlasReunited** [emilianavt/OpenSeeFace#42]
Hello!
After digging a bit with the program a little bit, it seems the "sock.sendto(packet, (target_ip, target_port))" line on 369 in facetracker.py simply doesn't function through a VPN connection 
Attached underneath is the error code produced

<img width="449" alt="debug" src="https://user-images.githubusercontent.com/65644424/178906340-907224e1-9f68-47e3-9c29-6303ef6f3bfb.png">

Extra info that may be useful for reproducing error and to find fix:
Windows 11 (64 bit, AMD CPU)
NordVPN Connection -> default protocol
Python 3.9 installed
Doesn't work with test using unbranded "USB Camera" as webcam, additionally with it processed through NVIDIA Broadcast's Virtual camera wouldn't work either

**Comment by emilianavt** [comment]
Hi! The tracker is just sending the packets to the specified IP address, which is set to 127.0.0.1 (localhost) by default. Make sure that the address is accessible through your VPN software and it should work (127.0.0.1 should always be accessible unless the system/VPN is very broken in some way). It's just very normal network code.

**Comment by AtlasReunited** [comment]
Hello!
Just checked again, just happens to be the "Split Tunneling" feature and not a bug indicative of using any specific VPN service
