### ISSUE TITLE
[SUGGESTION] officially support OpenSeeFace as a flatpak

### ISSUE THREAD

**Issue by orowith2os** [emilianavt/OpenSeeFace#43]
I am currently in the process of writing a Flatpak for OpenSeeFace, and have already gotten vpuppr (formerly openseefacegd) to work as a flatpak.
I think it would be beneficial for OpenSeeFace to officially support being ran as a flatpak, as it allows for one command to install (literally just flatpak install) and it wouldn't break on system python upgrades. 
This would probably only be beneficial to Linux, and maybe any other UNIX-like OSes.

**Comment by emilianavt** [comment]
I have never used anything flatpak related. What would be required to support this?

**Comment by orowith2os** [comment]
Making progress. When I get the pip dependencies to install inside of the environment, it'll be ready to use.
![image](https://user-images.githubusercontent.com/93224879/180102733-30bd73c8-76c7-46d8-9de2-b7aaf9d244b9.png)

**Comment by emilianavt** [comment]
What I meant is, would all that would be needed to include some control file like with e.g. poetry, or would I also have to make some kind of additional builds to upload when releasing new versions?

**Comment by orowith2os** [comment]
It seems to be able to just build using the method of release you're doing now, so no extra work needs to be done. To build the flatpak, just modify the manifest to change the archive (or git commit) to build from and it'll build whatever you tell it to with little to no issue.

**Comment by emilianavt** [comment]
Thank you, that sounds good then.

**Comment by orowith2os** [comment]
Still not done, waiting on some bug fixes in the flatpak-builder tools. I'll take another look at using prebuilt binaries though.

**Comment by emilianavt** [comment]
Oh, if you're still working on it, I'll keep the issue open!
