### ISSUE TITLE
Using the project for API

### ISSUE THREAD

**Issue by mohammadSHP** [emilianavt/OpenSeeFace#46]
Hi. Very nice work for this project!
I`m try to make an API with django and I have 2 question.

1)  Could we use video file instead of webcam? if yes, how?

2) Is there any feature that extract (save) detected faces?

thank you.

**Comment by emilianavt** [comment]
Hi.

1. Specify the video file with `-c`
2. Use the `--log-data` argument to write landmarks, bounding boxes, etc. to a file

**Comment by mohammadSHP** [comment]
nice. thank you very much

good luck
