### ISSUE TITLE
Extracting face with quaternion points

### ISSUE THREAD

**Issue by mohammadSHP** [emilianavt/OpenSeeFace#49]
Hi.
I'm trying to crop faces from original frame with quaternion points.
but there is a problem. The cropped image does not include the face and is only slightly smaller.
I think these points are not correct for cropping.
Do I using right point for cropping?
Do you have any idea for cropping frame and extract (save) face?

**Comment by emilianavt** [comment]
I suggest you iterate over the landmark points to create a bounding box from them instead. Quaternions specify the rotation of the face inside the real world, not the position in the frame.

**Comment by mohammadSHP** [comment]
thank you. Which variable should I use to create bbox?
