### ISSUE TITLE
Worse performance of released pytorch models

### ISSUE THREAD

**Issue by XChenZ** [emilianavt/OpenSeeFace#52]
Hello emilianavt, I'm trying to utilize the provided pytorch models (model.py) and weights to detect facial landmarks. However, I found its performance is worse than onnx version. An example is shown below (lm_model3 for both).

![comp](https://user-images.githubusercontent.com/39852186/226930959-94e392cf-0ed5-4908-b3fd-8eb2f607c900.png)

Do you have any suggestion? In my practice, I modify the model.py according to [this issue](https://github.com/emilianavt/OpenSeeFace/issues/9#issuecomment-710789545), and I adapt the tracker.py by replacing the onnx models (self.session and self.detection) with pytorch models (OpenSeeFaceLandmarks and OpenSeeFaceDetect). I follow the image preprocessing codes and postprocessing codes in the original tracker.py. I'm wondering if you could provide a demo tracking code for pytorch models. Any advice is appreciated!

**Comment by emilianavt** [comment]
Can you try using geffnet commit c450c12ae6ffb1757f62dde3c2765da3c10f6def?

**Comment by emilianavt** [comment]
If this is still an issue, please feel free to reopen it.

**Comment by vsfh** [comment]
same problem with geffnet commit c450c12ae6ffb1757f62dde3c2765da3c10f6def
