### ISSUE TITLE
Detection model without onnxruntime

### ISSUE THREAD

**Issue by JohnGebbie** [emilianavt/OpenSeeFace#54]
Hi @emilianavt,
I'm just using opencv without onnxruntime and got the landmarking working using the unoptimized models you shared in https://github.com/emilianavt/OpenSeeFace/issues/48, which is great.

I just tried the optimized detection model (mnv3_detection_opt.onnx) but not that surprisingly got the same layer error as with the optimized landmarking models.

It'd be fab if you could share the unoptimized detection model too.

**Comment by emilianavt** [comment]
Please try this: [mnv3_detection.zip](https://github.com/emilianavt/OpenSeeFace/files/11293953/mnv3_detection.zip)

**Comment by JohnGebbie** [comment]
It loads successfully. You're a star!
