### ISSUE TITLE
model loading error

### ISSUE THREAD

**Issue by arvindkrvartiya123** [emilianavt/OpenSeeFace#59]
Thanks for this awesome repo. i had a difficuilty in loading the model in unity. it is giving some kind or few layer aren't supported.

**Comment by emilianavt2** [comment]
Can you please post the exact error you are encountering?

**Comment by emilianavt2** [comment]
If you are trying to use the ONNX files with Barracuda, please see #48.

**Comment by arvindkrvartiya123** [comment]
![image_2023_06_21T07_34_40_986Z](https://github.com/emilianavt/OpenSeeFace/assets/111346724/9a90adda-0d98-4847-b415-da7946757b4d)

**Comment by arvindkrvartiya123** [comment]
it is giving "Asset import failed, 'Assets/Model/lm_modelU_opt.onnx'>OnnxImportException:Unknown type FusedConv encountered while parsing layer 293"

**Comment by emilianavt2** [comment]
In that case, the solution for #48 should apply.
