### ISSUE TITLE
why detect time always show 0.00ms?

### ISSUE THREAD

**Issue by NeekHua** [emilianavt/OpenSeeFace#6]
Hello,dear anchor.I‘m testing your project,and now have a problem.That is why detect time always show 0.00ms,test picture is following:
![image](https://user-images.githubusercontent.com/32665609/94096374-8332ab80-fe56-11ea-9928-816d5f4f2688.png)
Next  I found that parameter duration_fd mainly saved the detection time.and it's true.picture is following:
![image](https://user-images.githubusercontent.com/32665609/94096741-6ea2e300-fe57-11ea-95fc-73dcce08a909.png)
How should I modify to display the correct detection time? 
Thanks you watching!

**Comment by emilianavt** [comment]
0ms is correct. Face detection is only performed when less than `--max-faces` faces were detected last frame and only every `--scan-every` frames. If you want to make sure that face detection runs every frame, set `--max-faces` to a higher number of faces than are present in the input and set `--scan-every` to 0.

**Comment by NeekHua** [comment]
Oh,I see ,thank you for your help.Best wishes for you.
