### ISSUE TITLE
[Help Request] Opens exe, then it quickly closes?

### ISSUE THREAD

**Issue by LmbPX** [emilianavt/OpenSeeFace#65]
Hi sorry if this isn't where I ask for help, I'm new to this.

When opening facetracker.exe , it shows this text, then closes after a second.

![image](https://github.com/emilianavt/OpenSeeFace/assets/161145558/698183a3-178e-4798-84be-333551b65dcf)

Any reason why this might be happening? I might be doing something wrong.

Sorry if this is vague, really dunno anything

EDIT:
_sometimes_ it writes "No frame" briefly before closing. As closing is called before "No frame" shows, and it just depends on how long it takes to close

**Comment by LmbPX** [comment]
Not sure if I should delete this issue, cause it works now. However, I don't know why. I did try installing python and building it myself, and I did reinstall my camera drivers. But neither thing actually fixed the issue. Then, a while later, it just started working. I don't know why! 😅

**Comment by emilianavt** [comment]
Opening the `facetracker.exe` by double clicking it is unlikely to work. Instead, I recommend running the `run.bat` or manually calling the `facetracker.exe` with the necessary commandline arguments.
