### ISSUE TITLE
The tracking quality comparison video in the Read Me no longer works

### ISSUE THREAD

**Issue by TisFoolish** [emilianavt/OpenSeeFace#66]
Specifically this video https://cdn.discordapp.com/attachments/720652345540870237/1016320201807106118/OSFMediaPipe3DFR.mp4

This is due to Discord now requiring tracking URLs.  You can get a one by simply posting the above link into discord, but it appears that the URLs do eventually expire.  I suggest uploading to a dedicated video hosting service, like YouTube or Vimeo.

**Comment by emilianavt** [comment]
Thank you, I'll reupload the video when I get some time.

**Comment by emilianavt** [comment]
I have updated the link to a new one.
