### ISSUE TITLE
Bugfix #57 (np.int / np.float deprecation) not yet released

### ISSUE THREAD

**Issue by Danmyrer** [emilianavt/OpenSeeFace#67]
About 10 months ago, pull request #57 fixed a deprecation issue in `model.py` and `tracker.py`. Running `facetracker.py` works fine when using `master`, however if you try to run the [latest release](https://github.com/emilianavt/OpenSeeFace/releases/tag/v1.20.4) you still get an error:

```log
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Traceback (most r....
```

Creating a new release with the latest code should fix the issue :smile:

**Comment by emilianavt** [comment]
Until a new release is made, I recommend using the master branch or a supported version of numpy.
