### ISSUE TITLE
OpenSeeFace cannot run on Ubuntu 24.04

### ISSUE THREAD

**Issue by frozenMustelid** [emilianavt/OpenSeeFace#76]
OpenSeeFace can't run on Ubuntu 24.04. Some of the required library versions, like the ones for NumPy and ONNX, require an older Python version that does not exist in the repos, and even if you add some of the 20.04 repos to install Python 3.8 (24.04 comes with 3.12) then you can't use 3.8's pip or venv because those require packages that are mutually exclusive with packages necessary for the system Python. Breaking system Python breaks apt, so you can't just install them anyways.

I've tried using the newer Python libraries, and they don't work. NumPy specifically deprecated, then removed, some sort of float implementation within about 3 minor versions and I can't install a version older than this change on 24.04.

**Comment by emilianavt** [comment]
I believe if you check OSF out from git, the numpy incompatibility should be resolved and it should work with updated library versions. The release version is outdated though.

**Comment by frozenMustelid** [comment]
Thanks! I was using an extracted tarball of release version before, and the git clone version worked. I tested the face tracking with vpuppr and it connects and works again. Thanks again, both for your help and for making OSF in the first place.

(didn't close the issue myself as not sure if you want to close this as fixed now or leave it open until the next version change)
